configuration:
  defaultFolder: clinicaldata
  templateFolder: resources
  resourcesFolder: resources
  templateName: 'template.txt'
  errOutputFile: 'prueba.err'
  logOutputFile: 'prueba.out'
  shFileName: 'qsub.sh'
  keyToReplace: '%COMMAND%'
---
server:
  port: 9000
  contextPath: /ClinicalData
---
spring:
  profiles: local
  http:
    multipart:
      max-file-size: 2KB
      max-request-size: 2KB
logging:
  file: D:/dev_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: ERROR
    guru.springframework.controllers: ERROR
    org.hibernate: ERROR
datasource:
  clinicaldata:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod, default
  http:
    multipart:
      max-file-size: 2KB
      max-request-size: 2KB
logging:
  file: D:/dev_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: ERROR
    guru.springframework.controllers: ERROR
    org.hibernate: ERROR
datasource:
  clinicaldata:
    url: jdbc:mysql://localhost:3306/clinicaldata
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect